#!/bin/zsh
exes=("ffmpeg" "ffplay" "ffprobe")
dylibs=("libavcodec.61" "libavdevice.61" "libavfilter.10" "libavformat.61" "libavutil.59" "libpostproc.58" "libswresample.5" "libswscale.8")
dir="$(pwd)/out"

for dylib ($dylibs) {
    if [[ ! -f $dir/lib/$dylib.dylib ]] {
        echo Please update relocate_dylib.
        exit 1
    }
}

for exe ($exes) {
    for dylib ($dylibs) {
        install_name_tool -change $dir/lib/$dylib.dylib @executable_path/../lib/$dylib.dylib $dir/bin/$exe
    }
}
