#!/bin/bash

# ==============================================================================
# Build Script for vvdec (H.266/VVC Decoder)
# ==============================================================================
# Part of FFmpeg Build Script
# Licensed under Apache License, Version 2.0
#
# Features:
#   - H.266/VVC Decoding Support
#   - Profile-Guided Optimization (PGO)
#   - Dynamic discovery of training bitstreams from vvenc build
# ==============================================================================

# 1. Argument Processing
SCRIPT_DIR="$1"
SOURCE_DIR="$2"
TOOL_DIR="$3"
CPUS="$4"

# Load Helper Functions
if [ -f "$SCRIPT_DIR/functions.sh" ]; then
    . "$SCRIPT_DIR/functions.sh"
else
    echo "Error: functions.sh not found."
    exit 1
fi

echoSection "Building vvdec"

# 2. Version & Directory Setup
VERSION_FILE="$SCRIPT_DIR/../version/vvdec"
if [ -f "$VERSION_FILE" ]; then
    VERSION=$(cat "$VERSION_FILE")
else
    echo "Error: Version file not found."
    exit 1
fi

OS_NAME=$(uname -s)

# Prepare Source Directory
TARGET_SRC_DIR="$SOURCE_DIR/vvdec"
mkdir -p "$TARGET_SRC_DIR"
cd "$TARGET_SRC_DIR" || exit 1

# 3. Download Source
TARBALL="vvdec-${VERSION}.tar.gz"
URL="https://github.com/fraunhoferhhi/vvdec/archive/${VERSION}.tar.gz"

download "$URL" "$TARBALL"

SRC_DIR_NAME="vvdec-src"
mkdir -p "$SRC_DIR_NAME"
tar -zxf "$TARBALL" -C "$SRC_DIR_NAME" --strip-components=1
checkStatus $? "Unpack failed"
rm "$TARBALL"
cd "$SRC_DIR_NAME" || exit 1

# 4. PGO Configuration & Bitstream Discovery
# ------------------------------------------------------------------------------
# vvdec PGO requires valid .266 (VVC) bitstreams to decode.
# These are usually generated by the vvenc build script.

ENABLE_PGO="YES"
BITSTREAM_DIR=""

# Try to find where vvenc put the bitstreams
# We look into the sibling directory ../vvenc/vvenc-src (standard layout)
POSSIBLE_VVENC_SRC="$SOURCE_DIR/vvenc/vvenc-src"

if [ -d "$POSSIBLE_VVENC_SRC" ]; then
    BITSTREAM_DIR="$POSSIBLE_VVENC_SRC"
    echo "Found potential bitstream source: $BITSTREAM_DIR"
else
    echo "Warning: vvenc source directory not found. PGO might be skipped."
fi

# Validate presence of bitstreams
SAMPLES=("stefan_sif.266" "taikotemoto.266" "720p_bbb.266" "4k_bbb.266")
for sample in "${SAMPLES[@]}"; do
    if [ -z "$BITSTREAM_DIR" ] || [ ! -f "$BITSTREAM_DIR/$sample" ]; then
        echo "Warning: VVC bitstream $sample not found."
        ENABLE_PGO="NO"
        break
    fi
done

# Define PGO Flags
PGO_GEN_CFLAGS=""
PGO_GEN_CXXFLAGS=""
PGO_USE_CFLAGS=""
PGO_USE_CXXFLAGS=""

if [ "$OS_NAME" = "Darwin" ]; then
    # macOS (Clang)
    PGO_GEN_FLAGS="-fprofile-generate -mllvm -vp-counters-per-site=2048"
    PGO_GEN_CFLAGS="$PGO_GEN_FLAGS"
    PGO_GEN_CXXFLAGS="$PGO_GEN_FLAGS"
    
    # Locate llvm-profdata
    if command -v llvm-profdata >/dev/null 2>&1; then
        LLVM_PROFDATA="llvm-profdata"
    else
        XCODE_PATH=$(xcode-select -p 2>/dev/null)
        LLVM_PROFDATA="$XCODE_PATH/Toolchains/XcodeDefault.xctoolchain/usr/bin/llvm-profdata"
    fi
    
    if [ ! -x "$LLVM_PROFDATA" ] && [ "$ENABLE_PGO" = "YES" ]; then
        echo "Warning: llvm-profdata not found. Disabling PGO."
        ENABLE_PGO="NO"
    fi
else
    # Linux (GCC)
    PGO_GEN_FLAGS="-fprofile-generate"
    PGO_GEN_CFLAGS="$PGO_GEN_FLAGS"
    PGO_GEN_CXXFLAGS="$PGO_GEN_FLAGS"
fi

# 5. PGO Workflow
# ------------------------------------------------------------------------------
if [ "$ENABLE_PGO" = "YES" ]; then
    echoSection "PGO Step 1: Instrumentation"
    
    mkdir -p build-pgo
    # Configure instrumented build
    # -DVVDEC_INSTALL_VVDECAPP=ON: We need the app to run decoding tests
    cmake -S . -B build-pgo -G Ninja \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX="$(pwd)/install-pgo" \
        -DVVDEC_INSTALL_VVDECAPP=ON \
        -DBUILD_SHARED_LIBS=OFF \
        -DCMAKE_C_FLAGS="$PGO_GEN_CFLAGS" \
        -DCMAKE_CXX_FLAGS="$PGO_GEN_CXXFLAGS"
        
    checkStatus $? "PGO Config failed"
    
    # Build & Install
    cmake --build build-pgo -j "$CPUS"
    checkStatus $? "PGO Build failed"
    cmake --install build-pgo
    
    echoSection "PGO Step 2: Training"
    APP="./install-pgo/bin/vvdecapp"
    
    for sample in "${SAMPLES[@]}"; do
        echo "Decoding $sample for training..."
        # Decode and discard output (-o /dev/null)
        $APP -b "$BITSTREAM_DIR/$sample" -o /dev/null
        checkStatus $? "PGO training failed on $sample"
    done
    
    echoSection "PGO Step 3: Processing Profiles"
    
    if [ "$OS_NAME" = "Darwin" ]; then
        # Merge raw profiles
        $LLVM_PROFDATA merge -o default.profdata ./*.profraw
        checkStatus $? "Profile merge failed"
        
        ABS_PROF_PATH="$(pwd)/default.profdata"
        PGO_USE_CFLAGS="-fprofile-use=$ABS_PROF_PATH -Wno-backend-plugin"
        PGO_USE_CXXFLAGS="-fprofile-use=$ABS_PROF_PATH -Wno-backend-plugin"
        
        rm ./*.profraw
    else
        # Linux GCC uses .gcda files in-place
        PGO_USE_CFLAGS="-fprofile-use -Wno-missing-profile -Wno-coverage-mismatch"
        PGO_USE_CXXFLAGS="-fprofile-use -Wno-missing-profile -Wno-coverage-mismatch"
    fi
    
    # Clean up
    rm -rf build-pgo install-pgo
else
    echo "Skipping PGO (Missing bitstreams or tools)."
fi

# 6. Final Build
# ------------------------------------------------------------------------------
echoSection "Final Optimized Build"

mkdir -p build-final
# Configure optimized build
cmake -S . -B build-final -G Ninja \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX="$TOOL_DIR" \
    -DBUILD_SHARED_LIBS=OFF \
    -DVVDEC_ENABLE_LINK_TIME_OPT=ON \
    -DCMAKE_C_FLAGS="$PGO_USE_CFLAGS" \
    -DCMAKE_CXX_FLAGS="$PGO_USE_CXXFLAGS"

checkStatus $? "Final Config failed"

cmake --build build-final -j "$CPUS"
checkStatus $? "Final Build failed"

echo "Installing vvdec..."
cmake --install build-final
checkStatus $? "Final Install failed"

echoSection "vvdec Build Complete"
